# Generated by Django 4.0.4 on 2022-06-06 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_rename_slog_article_slug_remove_article_author_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='slug',
            field=models.SlugField(max_length=120),
        ),
    ]
