# Generated by Django 4.0.4 on 2022-06-13 09:21

from django.db import migrations
import embed_video.fields


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_rename_image_article_cover_image_alter_article_body'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='video',
            field=embed_video.fields.EmbedVideoField(),
        ),
    ]
