# Generated by Django 4.0.3 on 2022-03-26 18:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_orderitemonline'),
    ]

    operations = [
        migrations.DeleteModel(
            name='OrderItemOnline',
        ),
    ]
