# Generated by Django 4.0.3 on 2022-03-26 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_product_image_url_product_link_product_online_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='price_tl',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.IntegerField(null=True),
        ),
    ]
