# Generated by Django 4.0.3 on 2022-03-28 16:57

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_product_price_tl_alter_product_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='datetime',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
